### DISCUSSION TITLE
Hologram format and nashorn engine

### DISCUSSION THREAD

**Discussion by Flowsqy** [Flowsqy/ShopChest#1] [Ideas]
As the narhorn engine has been removed from the jdk, complex hologram formats are not evaluate and throws errors. The fastest solution to solve this problem is to include the nashorn engine in the jar file. But I think that shading tons and tons of thing like that is not very clever, especially from performance perspective. 
Another solution could be to remove the nashorn engine use completely from the plugin. But it will remove the possibility to create javascript scripts as they will not be evaluate.
So here comes my question. Does the script feature in hologram-format.yml is used only for arithmetic operations or is there people that use it in a more complex way ?
If everybody is using it to evaluate the stock with basic script, then I will implement classic operators (+ - * / %) and remove the possibility to do complex scripts.
Sharing your way of using it will be very appreciated.

**Comment by tooop4u** [comment]
Hi, basic math operators seem just fine on my part

**Comment by ken-kentan** [comment]
What do you mean about performance perspective?
I think there is no runtime overhead in the including js engine approach.

**Reply by Flowsqy** [reply]
You need to store whole strings, parse it and execute it. Just parse it one time and execute basic operation will always be faster. You also don't need to check every time for javascript special statement. On top of that, I think that shading a whole library to use only 2% of it is a little bit useless.
Even for maintabilty, you don't depend of a big program that can change at any moment the only method you use.

**Reply by ken-kentan** [reply]
I got your point.
So, are you going to improve the performance instead of just keeping this plugin features?
As you know, this pluhin already choose to use JS engine to format holo string, so there is no overhead compared with existing version.
The important thing in OSS is don't drop existing features as much as possible. We can't guess how many users using the feature.

And maintability, If we were implement own parser, it will make difficult to maintenance plugin instead of just using JS engine.

Actually, our server using this JS engine feature to format holo with complex operatipns.

**Reply by Flowsqy** [reply]
I agree with you and that's why I'm asking about the way people use the feature. I don't want to delete anything, just do it faster as it's a very repetitive task. You said that you use it for complex operations. Can you bring more details about that ?

**Reply by ken-kentan** [reply]
Sure.
for example:
```
lines:
  0:
    options:
      normal-shop:
        format: "%VENDOR%"
        requirements:
          - NORMAL_SHOP

      admin-shop:
        format: "&cAdmin Shop"
        requirements:
          - ADMIN_SHOP

  1:
    options:
      # enchant_book:
      #   format: "%ITEMNAME%(%ENCHANTMENT%) %AMOUNT%個"
      #   requirements:
      #     - ITEM_TYPE == "ENCHANTED_BOOK"
      # music_disc:
      #   format: "%ITEMNAME%(%MUSIC-TITLE%) %AMOUNT%個"
      #   requirements:
      #     - IS_MUSIC_DISC
      default:
        format: "%ITEMNAME% %AMOUNT%個"
        requirements: []

  2:
    options:
      enchant:
        format: "%ENCHANTMENT%"
        requirements:
          - HAS_ENCHANTMENT
      music_disc:
        format: "%MUSIC-TITLE%"
        requirements:
          - IS_MUSIC_DISC
      default:
        format: ""
        requirements: []

  3:
    options:
      out_of_stock:
        format: "&c在庫切れ"
        requirements:
          - IN_STOCK < AMOUNT
          - SELL_PRICE <= 0
          - '!ADMIN_SHOP'

      no_space:
        format: "&c空き不足"
        requirements:
          - CHEST_SPACE < AMOUNT
          - BUY_PRICE <= 0
          - '!ADMIN_SHOP'
          
      out_of_stock_and_no_space:
        format: "&c在庫切れ&r | &c空き不足"
        requirements:
          - IN_STOCK < AMOUNT
          - CHEST_SPACE < AMOUNT
          - BUY_PRICE > 0
          - SELL_PRICE > 0
          
      out_of_stock_and_sell:
        format: "&c在庫切れ&r | %SELL-PRICE% Sell"
        requirements:
          - IN_STOCK < AMOUNT
          - BUY_PRICE > 0
          - SELL_PRICE > 0
          
      buy_and_no_space:
        format: "Buy %BUY-PRICE% | &c空き不足"
        requirements:
          - CHEST_SPACE < AMOUNT
          - BUY_PRICE > 0
          - SELL_PRICE > 0
          
      buy-and-sell:
        format: "Buy %BUY-PRICE% | %SELL-PRICE% Sell"
        requirements:
          - BUY_PRICE > 0
          - SELL_PRICE > 0

      only-buy:
        format: "Buy %BUY-PRICE%"
        requirements:
          - BUY_PRICE > 0

      only-sell:
        format: "Sell %SELL-PRICE%"
        requirements:
          - SELL_PRICE > 0
```
